jms_serializer:
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
#            sensor_readings:
#                namespace_prefix: "App\\SensorReading\\Application\\Dto"
#                path: '%kernel.project_dir%/src/SensorReading/Infrastructure/Deserializer/Mapping/Application/Dto'
