twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    paths:
        'src/SensorReading/Bridge/Controller/Web/templates': ~

when@test:
    twig:
        strict_variables: true
